name: Publish image to GitHub GCR

on:
  workflow_dispatch:
    inputs:
      image-folder:
        description: 'The folder that contains the Dockerfile to build'
        required: true
      image-tag:
        description: 'The image tag to build'
        required: true

jobs:
  publish_to_public_grc:
    runs-on: ubuntu-latest

    steps:
      - name: Build info
        run: |
          echo "image folder ${{ github.event.inputs.image-folder }}"
          echo "image tag ${{ github.event.inputs.image-tag }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "${{ github.event.inputs.image-folder }}"
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.image-folder }}:${{ github.event.inputs.image-tag }}
